### ISSUE TITLE
如何简单使用？

### ISSUE THREAD

**Issue by yansheng836** [ddddyyyy/CSDN_Blog_Format#2]
你好，我看你这里好像只介绍了主要的实现方法，没有介绍如何简单使用，好像对不熟悉python的人不太友好啊，能不能添加这部分内容说明？比如：直接在主方法里面传入参数，介绍只要修改那个参数，然后如何运行该脚本；或者是直接通过命令行传入参数，介绍参数如何使用？

我试了下，好像只能下载一篇博客……不太懂怎么搞的

**Comment by ddddyyyy** [comment]
> 你好，我看你这里好像只介绍了主要的实现方法，没有介绍如何简单使用，好像对不熟悉python的人不太友好啊，能不能添加这部分内容说明？比如：直接在主方法里面传入参数，介绍只要修改那个参数，然后如何运行该脚本；或者是直接通过命令行传入参数，介绍参数如何使用？
> 
> 我试了下，好像只能下载一篇博客……不太懂怎么搞的

脚本存在点问题，现已经修复。添加了脚本的具体使用说明～～。
